name: GraphAC
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - rdkit
  - pytorch-geometric
  - dgl-cuda11.3
  - pot
  - numpy
  - certifi
