experiment_name: 'train-pcba-pna-6-layers-256-hidden-dims'

trainer: pcba
dataset: ogbg-molpcba
dataset_dir: /rds/user/xz398/hpc-work/learning-with-class/dataset
num_epochs: 50
batch_size: 512
log_iterations: 1
loss_func: BCEWithLogitsLoss
patience: 10000 # for early stopping etc
num_train: 50000

metrics:
  - ogbg-molpcba
main_metric: ogbg-molpcba
main_metric_goal: max # or min
collate_function: class_collate

optimizer: Adam
optimizer_params:
  lr: 5.0e-5

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700]
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  cooldown: 20
  factor: 0.6
  patience: 25
  min_lr: 1.0e-6
  threshold: 1.0e-4
  mode: 'min'
  verbose: True

# Model parameters
model_type: 'PNA'
model_parameters:
  target_dim: 128
  hidden_dim: 256
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  #e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum  =>  e^(log(0.001)/100) = 0.970
  #batch_norm_momentum: 0.93
  readout_layers: 2
  propagation_depth: 6
  dropout: 0.0
  aggregators:
    - mean
    - max
    - sum
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - mean
    - max
    - sum
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True


# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt