experiment_name: 'pre_train_ogbg_molpcba_loss_coeff_1_batch_32'

trainer: class
dataset: class_pcba
num_epochs: 10
batch_size: 32
log_iterations: 100
patience: 10000 # for early stopping etc
loss_func: CLASSLoss
num_train: 50000
seed: 42

metrics:
  - batch_variance
  - dimension_covariance
main_metric: loss
collate_function: class_collate

optimizer: Adam
optimizer_params:
  lr: 8.0e-5

optimizer2: Adam
optimizer2_params:
  lr: 8.0e-5

optimizer_critic: Adam
optimizer_critic_params:
  lr: 8.0e-5

optimizer_critic2: Adam
optimizer_critic2_params:
  lr: 8.0e-5

loss_coeff: 1.0

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700]
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  cooldown: 20
  factor: 0.6
  patience: 25
  min_lr: 1.0e-6
  threshold: 1.0e-4
  mode: 'min'
  verbose: True

# Model parameters
model_type: 'PNA'
model_parameters:
  target_dim: 32
  hidden_dim: 20
  readout_batchnorm: True
  readout_layers: 2
  aggregators:
    - sum
  scalers:
    - identity
  readout_aggregators:
    - sum
  residual: True

# Model parameters
model2_type: 'PNA'
model2_parameters:
  target_dim: 32
  hidden_dim: 10
  readout_batchnorm: True
  readout_layers: 2
  aggregators:
    - sum
  scalers:
    - identity
  readout_aggregators:
    - sum
  residual: True

# Model parameters
critic_type: 'BasicCritic'
critic_parameters:
  in_dim: 32
  out_dim: 32
  hidden_dim: 32
  layers: 1

# Model parameters
critic2_type: 'BasicCritic'
critic2_parameters:
  in_dim: 32
  out_dim: 32
  hidden_dim: 32
  layers: 1

# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt