experiment_name: 'pre-train_PNA_hidden_dim_64vs16'

trainer: class
dataset: class_hiv
num_epochs: 50
batch_size: 512
log_iterations: 1
eval_per_epochs: 1
iterations_per_model: 10
patience: 10000 # for early stopping etc
loss_func: CLASSLoss
num_train: 50000
seed: 42

metrics:
  - batch_variance
  - dimension_covariance
main_metric: loss
collate_function: class_collate

optimizer: Adam
optimizer_params:
  lr: 8.0e-5

optimizer2: Adam
optimizer2_params:
  lr: 8.0e-5

optimizer_critic: Adam
optimizer_critic_params:
  lr: 8.0e-5

optimizer_critic2: Adam
optimizer_critic2_params:
  lr: 8.0e-5

output_regularisation: 'sigmoid'
#loss_coeff1: 1.0
loss_coeff2: 0.5

#scheduler_step_per_batch: False
#lr_scheduler: WarmUpWrapper
#lr_scheduler_params:
#  warmup_steps: [700]
#  # parameters of scheduler to run after warmup
#  wrapped_scheduler: ReduceLROnPlateau
#  cooldown: 20
#  factor: 0.6
#  patience: 25
#  min_lr: 1.0e-6
#  threshold: 1.0e-4
#  mode: 'min'
#  verbose: True

# Model parameters
model_type: 'PNA'
model_parameters:
  target_dim: 256
  hidden_dim: 64
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
  #batch_norm_momentum: 0.93
  readout_layers: 2
  dropout: 0.0
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True

# Model parameters
model2_type: 'PNA'
model2_parameters:
  target_dim: 256
  hidden_dim: 16
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
  #batch_norm_momentum: 0.93
  readout_layers: 2
  dropout: 0.0
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - min
    - max
    - mean
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True

# Model parameters
critic_type: 'BasicCritic'
critic_parameters:
  in_dim: 256
  out_dim: 256
  hidden_dim: 256
  layers: 2

# Model parameters
critic2_type: 'BasicCritic'
critic2_parameters:
  in_dim: 256
  out_dim: 256
  hidden_dim: 256
  layers: 2

# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt
